### ISSUE TITLE
gtk-recordmydesktop: Can't access "Advanced" options menu

### ISSUE THREAD

**Issue by Xylemon** [PhantomX/slackbuilds#21]
Trying to do this results in a huge amount of Python garbage:

/usr/lib64/python2.7/site-packages/recordMyDesktop/rmdSelectThumb.py:79: GtkWarning: IA__gdk_image_put_pixel: assertion `y >= 0 && y < image->height' failed
  im2.put_pixel(k/stride,i/stride,im1.get_pixel(k,i))
/usr/lib64/python2.7/site-packages/recordMyDesktop/rmdPrefsWidget.py:239: GtkWarning: GtkSpinButton: setting an adjustment with non-zero page size is deprecated
  self.channelsSpinButton= gtk.SpinButton(self.channelsAdjustment, climb_rate=0.5, digits=0)
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/recordMyDesktop/rmdSimple.py", line 190, in advanced
    self.options=pW.prefsWidget(self,self.values,self.optionsOpen)
  File "/usr/lib64/python2.7/site-packages/recordMyDesktop/rmdPrefsWidget.py", line 410, in __init__
    self.__runJackLSP__()
  File "/usr/lib64/python2.7/site-packages/recordMyDesktop/rmdPrefsWidget.py", line 331, in __runJackLSP__
    (stdin,stdout,stderr)=os.popen3(['jack_lsp'],'t')
  File "/usr/lib64/python2.7/os.py", line 693, in popen3
    stderr=PIPE, close_fds=True)
  File "/usr/lib64/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

This is also with the stock Slackware Python package and the Python SlackBuild from this repo.

**Comment by PhantomX** [comment]
jack_lsp is from jack.

**Comment by Xylemon** [comment]
So does it require Jack to be installed for some reason?

**Comment by PhantomX** [comment]
I think so.

**Comment by Xylemon** [comment]
That worked, I'll also have to investigate why it thinks I'm using ALSA. Anyways thanks for the help, closing.
